ConcurrentModificationException extends RuntimeException
Возникает когда происходит конкурентное изменение объекта, когда такое изменение не разрешено. Например, когда поток пытается изменить коллекцию пока другой поток по ней итерируется.

Возникает не только в контексте многопоточки.
Fail-fast итераторы – отказоустойчивые итераторы

Если один поток выдает последовательность вызовов методов, которая нарушает контракт объекта, объект может выдать это исключение. Например, если поток изменяет коллекцию напрямую во время перебора коллекции с отказоустойчивым итератором, итератор выдаст это исключение.
Обратите внимание, что безотказное поведение не может быть гарантировано, так как, вообще говоря, невозможно дать какие-либо жесткие гарантии при наличии несинхронизированной параллельной модификации. Быстрые отказоустойчивые операции вызывают исключение ConcurrentModificationException в максимально возможной степени.
Поэтому было бы неправильно писать программу, корректность которой зависела бы от этого исключения: ConcurrentModificationException следует использовать только для обнаружения ошибок.


Столкнулся с этой ошибкой при попытке в цикле for each добавить элемент в коллекцию.
